name: LivePerson's Tech Blog
description:
meta_description: "LivePerson's Tech Blog"

markdown: redcarpet
highlighter: rouge
permalink: /:title.html
logo: false
paginate: 15
baseurl: /techblog
domain_name: 'http://livepersoninc.github.io'
port: 4001
comments: true

# Details for the RSS feed generator
url:            'http://livepersoninc.github.io/techblog'
author:         'LivePerson developers'