name: LP Tech Blog
description:
meta_description: "LP Tech Blog"

markdown: redcarpet
highlighter: pygments
permalink: /:title.html
logo: false
paginate: 15
baseurl: http://livepersoninc.github.io/techblog
domain_name: 'livepersoninc.github.io'
port: 4001
comments: true

# Details for the RSS feed generator
url:            'http://livepersoninc.github.io/techblog'
author:         'LivePerson developers'